# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: euromil.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\reuromil.proto\x12\x07\x65uromil\"/\n\x0fRegisterRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07\x63heckid\x18\x02 \x01(\t\" \n\rRegisterReply\x12\x0f\n\x07message\x18\x01 \x01(\t2N\n\x07\x45uromil\x12\x43\n\x0fRegisterEuroMil\x12\x18.euromil.RegisterRequest\x1a\x16.euromil.RegisterReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'euromil_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=26
  _globals['_REGISTERREQUEST']._serialized_end=73
  _globals['_REGISTERREPLY']._serialized_start=75
  _globals['_REGISTERREPLY']._serialized_end=107
  _globals['_EUROMIL']._serialized_start=109
  _globals['_EUROMIL']._serialized_end=187
# @@protoc_insertion_point(module_scope)
